### ISSUE TITLE
src missing

### ISSUE THREAD

**Issue by ghost** [LouisChen1992/Deep_Learning_in_Asset_Pricing#2]
src folder seems to be missing. Could you kindly upload it?

**Comment by LouisChen1992** [comment]
> src folder seems to be missing. Could you kindly upload it?

We are currently in the process of paper revision for a journal submission. We will share the source code later.

**Comment by yolsever** [comment]
Hi @LouisChen1992 , did you manage to submit the revised paper? I too would very much appreciate it if you could upload the src folder. Thanks!

**Comment by loganbnielsen** [comment]
@LouisChen1992 I too would appreciate if you could post the src folder. The current notebooks available show methods that were called to generate figures in the paper which really doesn't add utility to understanding the paper. The paper doesn't make it clear how the specifics of the networks were constructed so it'd be nice to see the code

**Comment by LouisChen1992** [comment]
Please take a look at this repo https://github.com/LouisChen1992/Deep_Learning_Asset_Pricing

**Comment by yolsever** [comment]
Thank you very much!
